# 2023.08.09
#
github_username: arafatm
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  toc:
    min_level: 2
    max_level: 5
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-titles-from-headings
  - jemoji

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  articles:
    output: true
    permalink: /:categories/:name

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# theme: jekyll-theme-hacker
#theme: minima