name: GHP Deploy

on:
  # Runs on pushes targeting the default branch
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: arafatm/ghp/.github/workflows/jekyll-gh-pages.yml@main
